version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

#  db:
#    image: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ok123456
#      MYSQL_USER: copart
#      MYSQL_PASSWORD: copart
#      MYSQL_DATABASE: copart

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    command: |
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py loaddata copart/fixtures/vehiclemakes.json &&
        python3 manage.py loaddata copart/fixtures/user.json &&
        python3 manage.py collectstatic --noinput &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery-worker-h:
    build: .
    command: celery -A copart worker --concurrency 4 --loglevel=INFO -n worker.high -Q high
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-worker-n:
    build: .
    command: celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.normal -Q normal
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-worker-l:
    build: .
    command: celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.low -Q low
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A copart beat --loglevel=INFO
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: