version: '2'

services:
  chrome:
    image: selenium/node-chrome:3.14.0-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-europium
    ports:
      - "4444:4444"

  db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - web

  web:
    build: ./backend
    restart: unless-stopped
    command: |
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py loaddata copart/fixtures/vehiclemakes.json &&
        python3 manage.py loaddata copart/fixtures/user.json &&
        python3 manage.py collectstatic --noinput &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db:db

  celery-worker-h:
    build: ./backend
    command: celery -A copart worker --concurrency 20 --loglevel=INFO -n worker.high -Q high
    restart: unless-stopped
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

  celery-worker-n:
    build: ./backend
    command: celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.normal -Q normal
    restart: unless-stopped
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

  celery-worker-l:
    build: ./backend
    command: celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.low -Q low
    restart: unless-stopped
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    command: celery -A copart beat --loglevel=INFO
    restart: unless-stopped
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
