version: '2'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    command: |
      sh -c "
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py loaddata copart/fixtures/vehiclemakes.json &&
        python3 manage.py loaddata copart/fixtures/user.json &&
        python3 manage.py collectstatic --noinput &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery-worker-h:
    build: .
    command: |
      sh -c "
        apt update &&
        apt install -y libxss1 libappindicator1 libindicator7 &&
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
        dpkg -i google-chrome*.deb &&
        apt install -y -f &&
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip &&
        apt install -y unzip &&
        unzip chromedriver_linux64.zip &&
        chmod +x chromedriver &&
        mv -f chromedriver /usr/local/bin/chromedriver &&
        celery -A copart worker --concurrency 9 --loglevel=INFO -n worker.high -Q high
      "
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-worker-n:
    build: .
    command: celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.normal -Q normal
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-worker-l:
    build: .
    command: |
      sh -c "
        apt update &&
        apt install -y libxss1 libappindicator1 libindicator7 &&
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
        dpkg -i google-chrome*.deb &&
        apt install -y -f &&
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip &&
        apt install -y unzip &&
        unzip chromedriver_linux64.zip &&
        chmod +x chromedriver &&
        mv -f chromedriver /usr/local/bin/chromedriver &&
        celery -A copart worker --concurrency 1 --loglevel=INFO -n worker.low -Q low
      "
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A copart beat --loglevel=INFO
    restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: